FROM node:16-alpine
WORKDIR /app
COPY src/session-backend/package.json src/session-backend/package-lock.json ./
RUN npm install
COPY src/components/Whiteboard.tsx ../components/Whiteboard.tsx
COPY src/session-backend/index.ts ./
COPY src/session-backend/tsconfig.json ./
CMD ["npx", "ts-node", "--esm", "index.ts"]
